apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: eks-debug-lab-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: eks-debug-lab-app
  ports:
    - name: http
      port: 8000
      targetPort: http
