apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: eks-debug-lab-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: eks-debug-lab-app
  ports:
    - name: redis
      port: 6379
      targetPort: redis
